### ISSUE TITLE
Ready for GA

### ISSUE THREAD

**Issue by jasperchui** [openshift-helm-charts/charts#61]
Infrastructure:
- [x] First submission requires manual approval #47 
   - [x] Slack notification and email notification to the team when manual approval is required.

PR Steps:
- [x] Ensure digest is same as the chart (source) submitted (PR #58)
- [x] HELM-172 | When the directory structure and the values within the chart are not matching, the PR job should fail

Checks: 
- [x] [HELM-118](https://issues.redhat.com/browse/HELM-118) | Run chart verifier on 4.7 version of OCP during chart submission
   - [x] #139 Add chart-testing support to verify-report.sh

- [x] Error message:   HELM-132 | PR job should leave some comment on PR itself stating what is wrong
- [x] Improve error messages #48  and #77
- [x]  Update error message with link to partner support url #49 (HELM-154)
- [x]  Capture PR details for issue analysis #50 
- [x]  HELM-155 | Add link to error log directly in the comment itself

 Documentation:
- [x] HELM-159 | Add GitHub README with documentation
